# Generated by Django 3.1.5 on 2021-04-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersignup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='_uploadprofilepicture_likes_+', to='usersignup.WebDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersignup.webdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersignup.webdetail')),
            ],
        ),
    ]
